### ISSUE TITLE
Remove PyTK as a dependency when generating the new manifest output

### ISSUE THREAD

**Issue by holy-the-sea** [AnotherPillow/TMXL2CP#1]
I think SMAPI will fail to load the mod if the dependency is listed as required?

**Comment by AnotherPillow** [comment]
Will work on this as soon as I can

**Comment by AnotherPillow** [comment]
[Fixed](https://github.com/AnotherPillow/TMXL2CP/commit/cde09a8b8a1f019e6c89734521938360cec0d691)
